local ls = require("luasnip")

-- Define a snippet creator shortcut
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

-- Define your LaTeX snippets
ls.add_snippets("tex", {
  -- Insert LaTeX Figure
  s("latexfigure", {
    t("\\begin{figure}[H]"),
    t({ "", "    \\centering" }),
    t({ "", "    \\includegraphics[scale=0.5]{" }), i(1), t("}"),
    t({ "", "    \\caption{" }), i(2), t("}"),
    t({ "", "    \\label{" }), i(3), t("}"),
    t({ "", "\\end{figure}" }),
  }),

  -- Insert LaTeX Equation
  s("latexequation", {
    t("\\begin{equation}\\label{"), i(2), t("}"),
    t({ "", "    " }), i(1),
    t({ "", "\\end{equation}" }),
  }),

  -- Insert LaTeX Align
  s("latexalign", {
    t("\\begin{align}"),
    t({ "", "    " }), i(1), t(" \\label{}"),
    t({ "", "\\end{align}" }),
  }),

  -- Insert LaTeX Matrix
  s("latexmatrix", {
    t("\\begin{bmatrix}"),
    t({ "", "  " }), i(1), t(" & "), i(2), t(" & "), i(3), t("\\\\"),
    t({ "", "  " }), i(4), t(" & "), i(5), t(" & "), i(6), t("\\\\"),
    t({ "", "  " }), i(7), t(" & "), i(8), t(" & "), i(9),
    t({ "", "\\end{bmatrix}" }),
  }),

  -- Insert LaTeX Code Block
  s("latexcodeblock", {
    t("\\begin{lstlisting}"),
    t({ "", "    " }), i(1),
    t({ "", "\\end{lstlisting}" }),
  }),

  -- Insert LaTeX Code Inline
  s("latexcode", {
    t("\\inlinecode{"), i(1), t("}"),
  }),

  -- LaTeX Template: Notes
  s("latex_notes_template", {
    t({
      "\\documentclass[11pt,letterpaper]{article}",
      "\\usepackage[top=3cm, bottom=2cm, left=2cm, right=2cm, columnsep=20pt]{geometry}",
      "\\usepackage{graphicx}",
      "\\usepackage[numbers]{natbib}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{ragged2e}",
      "\\usepackage[french]{babel}",
      "\\usepackage{listings}",
      "\\usepackage{color}",
      "\\usepackage{soul}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[export]{adjustbox}",
      "\\usepackage{caption}",
      "\\usepackage{amsmath}",
      "\\usepackage{amssymb}",
      "\\usepackage{float}",
      "\\usepackage{csquotes}",
      "\\usepackage{fancyhdr}",
      "\\usepackage{wallpaper}",
      "\\usepackage{siunitx}",
      "\\usepackage[indent]{parskip}",
      "\\usepackage{textcomp}",
      "\\usepackage{gensymb}",
      "\\usepackage{multirow}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{silence}",
      "\\usepackage{abstract}",
      "  \\renewcommand{\\abstractnamefont}{\\normalfont\\bfseries}",
      "  \\renewcommand{\\abstracttextfont}{\\normalfont\\itshape}",
      "\\usepackage{titlesec}",
      "  \\titleformat{\\section}{\\large\\bfseries}{\\thesection}{1em}{}",
      "  \\titleformat{\\subsection}{\\normalsize\\bfseries}{\\thesubsection}{1em}{}",
      "  \\titleformat{\\subsubsection}{\\normalsize\\bfseries}{\\thesubsubsection}{1em}{}",
      "\\setlength{\\parindent}{0pt}",
      "\\DeclareCaptionLabelFormat{mycaptionlabel}{#1 #2}",
      "\\captionsetup[figure]{labelsep=colon}",
      "\\captionsetup{labelformat=mycaptionlabel}",
      "\\captionsetup[figure]{name={Figure }}",
      "\\WarningFilter{caption}{Unused \\captionsetup[figure]}",
      "\\newcommand{\\inlinecode}{\\normalfont\\texttt}",
      "\\usepackage{enumitem}",
      "\\setlist[itemize]{label=\\textbullet}",
      "",
      "\\begin{document}",
      "\\pagestyle{fancy}",
      "\\setlength{\\headheight}{14pt}",
      "\\renewcommand{\\headrulewidth}{0pt}",
      "\\fancyfoot[R]{\\thepage}",
      "\\pagestyle{fancy}",
      "\\fancyhf{}",
      "\\renewcommand{\\headrulewidth}{1pt}",
      "\\thispagestyle{fancy}",
      "\\fancyhead[L]{\\textbf{" }), i(1), t("}}"),
    t({ "", "\\fancyhead[C]{" }), i(2), t("}"),
    t({ "", "\\fancyhead[R]{\\today}"}),
    t({ "", "\\fancyfoot[R]{\\thepage}"}),
    t({ "", "\\pagenumbering{arabic}"}),
    t({ "", "\\setcounter{page}{1}"}),
    t({ "", "%----------------------------------------------------"}),
    t({ "", "\\begin{onecolabstract}", "", "  \\vspace{4mm}", "\\end{onecolabstract}", "", "\\section{" }), i(3), t("}"),
    t({ "", "" }), i(4), t({ "", "", "\\end{document}" })
  }),

  -- LaTeX Template: Project
  s("latex_project_template", {
    t({
      "\\documentclass[11pt,letterpaper]{article}",
      "\\usepackage[top=3cm, bottom=2cm, left=2cm, right=2cm, columnsep=20pt]{geometry}",
      "\\usepackage{graphicx}",
      "% \\usepackage[numbers]{natbib}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{ragged2e}",
      "\\usepackage[french]{babel}",
      "\\usepackage{listings}",
      "\\usepackage{color}",
      "\\usepackage{soul}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[export]{adjustbox}",
      "\\usepackage{caption}",
      "\\usepackage{amsmath}",
      "\\usepackage{amssymb}",
      "\\usepackage{float}",
      "\\usepackage{csquotes}",
      "\\usepackage{fancyhdr}",
      "\\usepackage{wallpaper}",
      "\\usepackage{siunitx}",
      "\\usepackage[indent]{parskip}",
      "\\usepackage{textcomp}",
      "\\usepackage{gensymb}",
      "\\usepackage{multirow}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{abstract}",
      "  \\renewcommand{\\abstractnamefont}{\\normalfont\\bfseries}",
      "  \\renewcommand{\\abstracttextfont}{\\normalfont\\itshape}",
      "\\usepackage{titlesec}",
      "  \\titleformat{\\section}{\\large\\bfseries}{\\thesection}{1em}{}",
      "  \\titleformat{\\subsection}{\\normalsize\\bfseries}{\\thesubsection}{1em}{}",
      "  \\titleformat{\\subsubsection}{\\normalsize\\bfseries}{\\thesubsubsection}{1em}{}",
      "",
      "%----------------------------------------------------",
      "",
      "\\setlength{\\parindent}{0pt}",
      "\\DeclareCaptionLabelFormat{mycaptionlabel}{#1 #2}",
      "\\captionsetup[figure]{labelsep=colon}",
      "\\captionsetup{labelformat=mycaptionlabel}",
      "\\captionsetup[figure]{name={Figure }}",
      "\\newcommand{\\inlinecode}{\\normalfont\\texttt}",
      "\\usepackage{enumitem}",
      "\\setlist[itemize]{label=\\textbullet}",
      "",
      "\\begin{document}",
      "\\begin{titlepage}",
      "\\center",
      "",
      "\\begin{figure}",
      "    \\ThisULCornerWallPaper{.4}{Polytechnique_signature-RGB-gauche_FR.png}",
      "\\end{figure}",
      "\\vspace*{2 cm}",
      "",
      "\\textsc{\\Large \\textbf{PHS???? --} Nom du cours}\\\\[0.5cm]",
      "\\large{\\textbf{Équipe : ??}}\\\\[1.5cm]",
      "",
      "\\rule{\\linewidth}{0.5mm} \\\\[0.5cm]",
      "\\Large{\\textbf{Titre}} \\\\[0.2cm]",
      "\\text{Sous-titre}\\\\",
      "\\rule{\\linewidth}{0.2mm} \\\\[2.3cm]",
      "",
      "\\large{\\textbf{Présenté à}\\\\",
      "  Professeur Prof\\\\[2.5cm]",
      "  \\textbf{Par :}\\\\",
      "  Émile \\textbf{Guertin-Picard} (2208363)\\\\[3cm]}",
      "",
      "\\large{\\today\\\\",
      "Département de Génie Physique\\\\",
      "Polytechnique Montréal\\\\}",
      "",
      "\\end{titlepage}",
      "",
      "%----------------------------------------------------",
      "",
      "\\tableofcontents",
      "\\pagenumbering{roman}",
      "\\newpage",
      "",
      "\\pagestyle{fancy}",
      "\\setlength{\\headheight}{14pt}",
      "\\renewcommand{\\headrulewidth}{0pt}",
      "\\fancyfoot[R]{\\thepage}",
      "",
      "\\pagestyle{fancy}",
      "\\fancyhf{}",
      "\\renewcommand{\\headrulewidth}{1pt}",
      "\\fancyhead[L]{\\textbf{PHS????}}",
      "\\fancyhead[C]{Sujet}",
      "\\fancyhead[R]{Équipe ??}",
      "\\fancyfoot[R]{\\thepage}",
      "",
      "\\pagenumbering{arabic}",
      "\\setcounter{page}{1}",
      "",
      "%----------------------------------------------------",
      "",
      "\\begin{onecolabstract}",
      "",
      "",
      "",
      "  \\vspace{4mm}",
      "\\end{onecolabstract}",
      "",
      "\\section{??????????????}",
      "",
      "",
      "",
      "\\clearpage",
      "",
      "% \\bibliographystyle{plain}",
      "% \\bibliography{My_Library}",
      "",
      "\\end{document}"
    })
  }),

  -- LaTeX Template: Homework
  s("latex_homework_template", {
    t({
      "\\documentclass[11pt,letterpaper]{article}",
      "\\usepackage[top=3cm, bottom=2cm, left=2cm, right=2cm, columnsep=20pt]{geometry}",
      "\\usepackage{graphicx}",
      "% \\usepackage[numbers]{natbib}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage{ragged2e}",
      "\\usepackage[french]{babel}",
      "\\usepackage{listings}",
      "\\usepackage{color}",
      "\\usepackage{soul}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage[export]{adjustbox}",
      "\\usepackage{caption}",
      "\\usepackage{amsmath}",
      "\\usepackage{amssymb}",
      "\\usepackage{float}",
      "\\usepackage{csquotes}",
      "\\usepackage{fancyhdr}",
      "\\usepackage{wallpaper}",
      "\\usepackage{siunitx}",
      "\\usepackage[indent]{parskip}",
      "\\usepackage{textcomp}",
      "\\usepackage{gensymb}",
      "\\usepackage{multirow}",
      "\\usepackage[hidelinks]{hyperref}",
      "\\usepackage{abstract}",
      "  \\renewcommand{\\abstractnamefont}{\\normalfont\\bfseries}",
      "  \\renewcommand{\\abstracttextfont}{\\normalfont\\itshape}",
      "\\usepackage{titlesec}",
      "  \\titleformat{\\section}{\\large\\bfseries}{\\thesection}{1em}{}",
      "  \\titleformat{\\subsection}{\\normalsize\\bfseries}{\\thesubsection}{1em}{}",
      "  \\titleformat{\\subsubsection}{\\normalsize\\bfseries}{\\thesubsubsection}{1em}{}",
      "",
      "%----------------------------------------------------",
      "",
      "\\setlength{\\parindent}{0pt}",
      "\\DeclareCaptionLabelFormat{mycaptionlabel}{#1 #2}",
      "\\captionsetup[figure]{labelsep=colon}",
      "\\captionsetup{labelformat=mycaptionlabel}",
      "\\captionsetup[figure]{name={Figure }}",
      "\\newcommand{\\inlinecode}{\\normalfont\\texttt}",
      "\\usepackage{enumitem}",
      "\\setlist[itemize]{label=\\textbullet}",
      "",
      "\\begin{document}",
      "\\begin{titlepage}",
      "\\center",
      "",
      "\\begin{figure}",
      "    \\ThisULCornerWallPaper{.4}{Polytechnique_signature-RGB-gauche_FR.png}",
      "\\end{figure}",
      "\\vspace*{2 cm}",
      "",
      "\\textsc{\\Large \\textbf{PHS???? --} Nom du cours}\\\\[0.5cm]",
      "\\large{\\textbf{Équipe : ??}}\\\\[1.5cm]",
      "",
      "\\rule{\\linewidth}{0.5mm} \\\\[0.5cm]",
      "\\Large{\\textbf{Titre}} \\\\[0.2cm]",
      "\\text{Sous-titre}\\\\",
      "\\rule{\\linewidth}{0.2mm} \\\\[2.3cm]",
      "",
      "\\large{\\textbf{Présenté à}\\\\",
      "  Professeur Prof\\\\[2.5cm]",
      "  \\textbf{Par :}\\\\",
      "  Émile \\textbf{Guertin-Picard} (2208363)\\\\[3cm]}",
      "",
      "\\large{\\today\\\\",
      "Département de Génie Physique\\\\",
      "Polytechnique Montréal\\\\}",
      "",
      "\\end{titlepage}",
      "",
      "%----------------------------------------------------",
      "",
      "\\pagenumbering{roman}",
      "\\newpage",
      "",
      "\\pagestyle{fancy}",
      "\\setlength{\\headheight}{14pt}",
      "\\renewcommand{\\headrulewidth}{0pt}",
      "\\fancyfoot[R]{\\thepage}",
      "",
      "\\pagestyle{fancy}",
      "\\fancyhf{}",
      "\\renewcommand{\\headrulewidth}{1pt}",
      "\\fancyhead[L]{\\textbf{PHS????}}",
      "\\fancyhead[C]{Sujet}",
      "\\fancyhead[R]{Équipe ??}",
      "\\fancyfoot[R]{\\thepage}",
      "",
      "\\pagenumbering{arabic}",
      "\\setcounter{page}{1}",
      "",
      "%----------------------------------------------------",
      "",
      "\\section{?????????????}",
      "",
      "",
      "",
      "\\clearpage",
      "",
      "\\end{document}"
    })
  }),
})

-- Function to trigger a snippet by name
local function expand_snippet(snippet_name)
  for _, snippet in ipairs(ls.get_snippets("tex")) do
    if snippet.trigger == snippet_name then
      ls.snip_expand(snippet)
      return
    end
  end
  print("Snippet not found: " .. snippet_name)
end

-- Make the function accessible from other Lua files
return {
  expand_snippet = expand_snippet
}
